name: study_streamlit_app
dependencies:
  - numpy
  - pandas
  - streamlit
  - os
  - itertools
  - sys
  - functools
  - pathlib
  - datetime 
  - codecs
  - pickle
  - matplotlib
  - pydeck
  - plotly